### ISSUE TITLE
Trouble running the tool

### ISSUE THREAD

**Issue by tgram75** [GPUOpen-Tools/RGA#12]
I am trying to run the tool with a very simple pixel shader to generate the isa. No matter how simple I make the shader the tool fails to generate any output. It also doesn't matter what ASIC I target (they all fail).

I invoke the tool like this:
`rga.exe -c Oland -s hlsl -f main -p ps_4_0 --isa test.isa TestPS.hlsl`

TestPS.hlsl contains:
```
struct PSIn
{
    float2 uv : TEXTURE0;
};

float4 main(PSIn psIn) : SV_Target
{
    return float4(1.0,0.0,0.0,1.0);
}
```

And I get output like this (same output with `--verbose` option on):
```
atidxx64.dll AmdDxGsaCompileShader failed.
Building for Oland... failed.
```

I am using the Crimson Relive 17.7.1-July10 driver (`Non-WHQL-Win10-64Bit-Radeon-Software-Crimson-ReLive-17.7.1-July10.exe`) on Win10 64-bit Enterprise (rs2).

Are there any known issues?

**Comment by AmitBM** [comment]
Hi tgram75,

We tested the source code that you provided with the same command and system configuration, but could not reproduce the issue.

**Comment by tgram75** [comment]
I just tried downloading the source and building locally. I stepped through the code until the `beProgramBuilderDX::AmdDxGsaCompileShaderWrapper` call where it fails. Quick look at the vars seem to indicate `atidxx64.dll` loaded alright and the entry points were found correctly.

Are there any requirements that the AMD video card must be the primary/ only adapter in the system for this to work? I have multiple videocards in my machine and the AMD card is not the primary one. I also don't have any outputs connected to the RX550.

**Comment by AmitBM** [comment]
Hi tgram75,

In that case, it sounds like this issue is related to the Windows Driver Store.  Since your primary card is not an AMD GPU, the driver fails to locate a required component and the compilation process fails. Even if you will switch the primary video card to be an AMD GPU, it is not guaranteed that the compilation process will succeed. We have already ran into scenarios in the past where multiple AMD GPUs on the same system caused a similar issue. 
We will look into that, and try to provide a fix in one of the upcoming releases.
Thanks for reporting this issue.

**Comment by tgram75** [comment]
@AmitBM, I did notice a fair amount of the driver files got installed under `C:\Windows\System32\DriverStore\FileRepository\c0315940.inf_amd64_2b462f080682210e`. Are you saying I can work around this issue by setting up a box with just the RX550 card in? Or is there any way I can hardcode the tool to look for the required component dll in the right spot?

**Comment by AmitBM** [comment]
Hi tgram75,

Unfortunately, there is no way to hardcode this in the tool.
If our assumption is correct, and the problem that you encounter is indeed caused by the fact that you have multiple GPUs installed on your system, then bringing up a fresh machine with a single AMD GPU should solve this issue.

**Comment by tgram75** [comment]
I will try a fresh box with just the RX550 in next week and let you know. 👍 for prompt support!

**Comment by AmitBM** [comment]
Hi tgram75,
[RGA 1.2](https://github.com/GPUOpen-Tools/RGA/releases/tag/1.2.0.0) now supports multi-GPU system configurations in DirectX mode, and this should solve your issue. Please see the [RGA 1.2 Release Notes document ](https://github.com/GPUOpen-Tools/RGA/releases/download/1.2.0.0/RGA-1.2-ReleaseNotes.pdf) for more details.

**Comment by tgram75** [comment]
Thanks for looking into it - I'll give it a shot. I started using RenderDoc's recently added support for ISA disassembly - it is very convenient to have the feature at hand directly in a capture tool (see https://github.com/baldurk/renderdoc/wiki/GCN-ISA).

**Comment by AmitBM** [comment]
Hi tgram75,
RenderDoc uses RGA to extract GCN ISA disassembly, so you should expect a similar behavior.
Please let us know if the support for multi-GPU system configurations in RGA 1.2 solved your issue.

**Comment by tgram75** [comment]
I installed RGA 1.2 and still get same error message as originally reported.

**Comment by tgram75** [comment]
Errh I'm a clown.. I did not read the manual. I though the support for multi-adapter was automatic. When setting the adapter with the proper parameters every works.

Thanks for fixing it. Closing issue.
