### ISSUE TITLE
Targeting OpenCL on Windows

### ISSUE THREAD

**Issue by hogstres** [GPUOpen-Tools/RGA#18]
Hi!

My apologies for an issue probably due to my own inaptitude and understanding of the context . I assumed it would be possible to use the offline rocm compiler included in the 1.4 release to produce some binary form that could be loaded and with clCreateProgramWithBinary+clBuildProgram under Windows. Regardless of what I try, the hsacobj ELF produced is rejected with the message "The binary is incorrect or incomplete. Finalization to ISA couldn't be performed.".

Is it possible to do what I'm trying to do? The main reason is that I observe a much better VGPR usage in the live reg analysis with the rocm compiler that would allow for more scheduled wavefronts. 

Thanks,
hogstres

**Comment by AmitBM** [comment]
For the rocm-cl mode, RGA uses the Lightning Compiler, which is currently limited to ROCm. Since ROCm only supports Linux, it is not possible to use the binaries which are produced by it on Windows, since AMD’s OpenCL runtime on Windows currently uses a different compiler that has a different type of binary object. You should, however, be able to use the generated binaries on a ROCm-capable Linux machine. We will be happy to hear how it went.
