### ISSUE TITLE
CLI analysis csv header doesn't match values for HLSL/CL

### ISSUE THREAD

**Issue by kstuedem** [GPUOpen-Tools/RGA#23]
"SGPR_SPILLS" and  "VGPR_SPILLS" are alway get added to the CSV header even though the values aren't when analyzing HLSL shaders/CL programs.

**Comment by AmitBM** [comment]
Hi kstuedem,

Thank you for reporting this issue. We will look into this.

**Comment by AmitBM** [comment]
Hi kstuedem,

We will not remove any columns from the CSV file, since we would like to allow users to have a single parser for all RGA modes. We will make sure that all modes report the same set of attributes, and, if any attribute is irrelevant, we will place N/A values rather than leaving empty cells to signal this.

Thanks again for reporting this issue.

**Comment by AmitBM** [comment]
Hi kstuedem,

With RGA 2.0.1, which was released today, we aligned all modes to report the same set of attributes.
