### ISSUE TITLE
Compile and disassamble shader on machine withouth AMD Card

### ISSUE THREAD

**Issue by giordi91** [GPUOpen-Tools/RGA#28]
Is it possible to use the RGA for disassembling a shader on a machine without AMD GPU?
When I open it only lets me deal with CL files, not HLSL ones. And If I force import one and try to build the CL compiler of course fails.

Please advise

Best regards

M.

**Comment by kpyzhov** [comment]
Hi M,

The RGA GUI supports CL mode only so far, so it is not possible to use GUI for HSLS shaders.
You can use the RGA command-line tool (rga.exe) for disassembling HLSL shaders (use rga.exe --help for details). However, you will need AMD GPU and AMD graphic driver installed on the machine since RGA calls shader back-end compiler provided by the graphic driver in HLSL mode.

Thanks!
-- Konstantin.

**Comment by giordi91** [comment]
Thank you for the feedback.
