### ISSUE TITLE
Legacy OpenCL compile

### ISSUE THREAD

**Issue by ppereirasky** [GPUOpen-Tools/RGA#36]
Hi There,

Why isn't it possible to legacy compile OpenCL directly from the GUI. Is there any limitation? Why it's only possible to compile ROCm OpenCl from the GUI?

Thanks in advance.

**Comment by b-sumner** [comment]
I don't know what GUI you have in mind.  But the only standard compiler for OpenCL C is embedded within the OpenCL runtime and invoked with, e.g. clBuildProgram().  For OpenCL 2.1 and 2.2 an offline compiler is needed to compile the source into conformant SPIR-V which is then passed into clCreateProgramWithIL().

**Comment by AmitBM** [comment]
Hi ppereirasky,

RGA’s legacy OpenCL mode uses AMD’s OpenCL runtime to compile the code. Due to implementation details of AMD’s OpenCL runtime, the compilation chain that is being used may differ across systems and configurations (OS, installed physical GPU, etc.). This makes it hard to provide a clear UI for code optimization for the legacy mode. ROCm, however, consistently uses the LLVM-based Lightning Compiler. By only targeting ROCm OpenCL and ignoring the legacy mode, RGA can provide a clear interface in the GUI to support those who optimize OpenCL code for ROCm.

**Comment by ppereirasky** [comment]
I understand - thanks for the answer. I'm only using the legacy mode (from the CLI), but would have loved to use it directly from the GUI, with the wonderful ISA code highlight, to quickly "see" what the compiler is doing. Unfortunately it's not possible.

**Comment by AmitBM** [comment]
Hi ppereirasky,

Thanks for expressing your desire to see legacy OpenCL supported in the GUI - we will take a note of that.
